services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=nikborsh.ufo@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/letsencrypt/acme.json"
    networks:
      - proxy

  daoserver:
    image: ${IMAGE}:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - daovolume:/dockervolumes
    env_file:
      - ./.env
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.daoserver.rule=Host(`dao-api.crm-system.art`)"
      - "traefik.http.routers.daoserver.entrypoints=websecure"
      - "traefik.http.routers.daoserver.tls.certresolver=myresolver"
      - "traefik.http.services.daoserver.loadbalancer.server.port=8080"
      # WebSocket support
      - "traefik.http.routers.daoserver.middlewares=websocket-headers"
      - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Connection=Upgrade"
      - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Upgrade=websocket"
      - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Sec-WebSocket-Protocol=chat,superchat"

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - proxy

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`logs.crm-system.art`)"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
      - "traefik.http.routers.dozzle.tls.certresolver=myresolver"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      # Basic Auth Middleware (Login: admin, Password: changeme) - Generate new one later!
      # htpasswd -nb admin changeme -> admin:$apr1$....
      - "traefik.http.middlewares.auth.basicauth.users=admin:$apr1$Run5/s.n$L.e/X/w.y.z.a.b.c.d.e"
      - "traefik.http.routers.dozzle.middlewares=auth"

volumes:
  daovolume:
  mongo-data:

networks:
  proxy:
    name: proxy
