entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
  # UDP entrypoint for TURN server
  turn:
    address: ':3478/udp'

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: 'nikborsh.ufo@gmail.com'
      storage: 'acme.json'
      httpChallenge:
        entryPoint: web
